---
title: "IndikatorGizi"
author: "Arya Candra"
date: "4/26/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = F,
                      warning = F,
                      comment = "",
                      fig.width = 10,
                      fig.asp = 0.618)
```

```{r}
library(tidyverse)
library(readxl)
library(ggtext)

data_stunting_2019 <- read_excel("data_stunting.xlsx",
                                 sheet = "Tahun2019")
data_stunting_2019
data_stunting_2020 <- read_excel("data_stunting.xlsx",
                                 sheet = "Tahun2020")
data_stunting_2020
data_stunting_2021 <- read_excel("data_stunting.xlsx",
                                 sheet = "Tahun2021")
data_stunting_2021
data_stunting_2022 <- read_excel("data_stunting.xlsx",
                                 sheet = "Tahun2022")
data_stunting_2022
```

```{r}
dim(data_stunting_2019)
dim(data_stunting_2020)
dim(data_stunting_2021)
dim(data_stunting_2022)
```

```{r}
library(sf)
peta <- read_sf("Data Administrasi/Administrasi_Provinsi.shp")
peta

peta_2020 <-  peta %>%
  left_join(data_stunting_2020,
            by = c("PROVINSI"="Provinsi"))
peta_2020

peta_2021 <- peta %>%
  left_join(data_stunting_2021,
            by = c("PROVINSI"="Provinsi"))
peta_2021
```

# Visualisasi Dot Plot


```{r}
ggthemr::ggthemr("fresh")

nasional_2020 <- data_stunting_2020 %>%
  summarise(
    Prevalensi = (sum(sPendek)+sum(sSangatPendek))*100/sum(JumlahBalita)
  )

nasional_2020 <- data.frame(
  Provinsi = "Indonesia",
  Prevalensi = nasional_2020$Prevalensi
)

nasional_2020

bind_rows(data_stunting_2020, nasional_2020)

dot_plot_2020 <- data_stunting_2020 %>%
  bind_rows(nasional_2020) %>%
  mutate(
    Provinsi = case_when(
      Provinsi == "DKI JAKARTA" ~ "DKI Jakarta",
      TRUE ~ str_to_title(Provinsi)),
    Provinsi = fct_reorder(Provinsi, Prevalensi),
    Kondisi = case_when(
      Prevalensi > nasional_2020$Prevalensi ~ "Buruk",
      Prevalensi <= nasional_2020$Prevalensi ~ "Baik"),
    Kondisi = as.factor(Kondisi)) %>%
  ggplot(aes(x = Prevalensi,
             y = Provinsi,
             color = Kondisi))+
  geom_point(size = 2.5)+
  labs(
    title = "Masih Terdapat banyak Provinsi yang Memiliki Prevalensi Stunting Lebih dari Nasional",
    subtitle = "Tahun 2020",
    x = "Prevalensi (%)",
    caption = "**Sumber Data : Aksi Bangda Kemendagri**")+
  scale_color_manual(values = c("green", "red"))+
  theme(
    plot.title = element_markdown(hjust = 0),
    axis.title.y = element_blank(),
    axis.text.y =  element_markdown(color = c(rep("grey30", 16),
                                              "blue",
                                              rep("grey30", 18)),
                                    size = 12),
    legend.position = "top",
    plot.caption = element_markdown())
dot_plot_2020

# ggsave("dot_plot_2020.png",
#        plot = dot_plot_2020,
#        device = "png",
#        width = unit(16, "inch"),
#        height = unit(10, "inch"))
```

```{r}
ggthemr::ggthemr("fresh")

nasional_2021 <- data_stunting_2021 %>%
  summarise(
    Prevalensi = (sum(sPendek)+sum(sSangatPendek))*100/sum(JumlahBalita)
  )

nasional_2021 <- data.frame(
  Provinsi = "Indonesia",
  Prevalensi = nasional_2021$Prevalensi
)

nasional_2021

bind_rows(data_stunting_2021, nasional_2021)

dot_plot_2021 <- data_stunting_2021 %>%
  bind_rows(nasional_2021) %>%
  mutate(
    Provinsi = case_when(
      Provinsi == "DKI JAKARTA" ~ "DKI Jakarta",
      TRUE ~ str_to_title(Provinsi)),
    Provinsi = fct_reorder(Provinsi, Prevalensi),
    Kondisi = case_when(
      Prevalensi > nasional_2021$Prevalensi ~ "Buruk",
      Prevalensi <= nasional_2021$Prevalensi ~ "Baik"),
    Kondisi = as.factor(Kondisi)) %>%
  ggplot(aes(x = Prevalensi,
             y = Provinsi,
             color = Kondisi))+
  geom_point(size = 2.5)+
  labs(
    title = "*Secara Umum*, Provinsi di Indonesia Sudah Mengurangi Prevalensi Stunting",
    subtitle = "Tahun 2021",
    x = "Prevalensi (%)",
    caption = "**Sumber Data : Aksi Bangda Kemendagri**")+
  scale_color_manual(values = c("green", "red"))+
  scale_x_continuous(limits = c(0, 30))+
  theme(
    plot.title = element_markdown(hjust = 0),
    axis.title.y = element_blank(),
    axis.text.y =  element_markdown(color = c(rep("grey30", 16),
                                              "blue",
                                              rep("grey30", 18)),
                                    size = 12),
    legend.position = "top",
    plot.caption = element_markdown())

dot_plot_2021

# ggsave("dot_plot_2021.png",
#        plot = dot_plot_2021,
#        device = "png",
#        width = unit(16, "inch"),
#        height = unit(10, "inch"))
```

# Histogram

```{r}
hist_2020 <- ggplot(data = data_stunting_2020,
       aes(Prevalensi))+
  geom_density(
    aes(y = ..count..),
    size = 2,
    color = "slateblue")+
  labs(
    title = "Distribusi Prevalensi *Stunting* di Indonesia Berbentuk **Menceng Kanan**  
    Terdapat Daerah dengan Prevalensi Stunting Relatif Tinggi",
    subtitle = "Tahun 2020",
    x = "Prevalensi (%)",
    caption = "**Sumber Data : Aksi Bangda Kemendagri**")+
  scale_y_continuous(limits =  c(0, 3),
                     breaks = seq(0, 3, 1))+
  scale_x_continuous(breaks = seq(0, 30, 5))+
  theme(
    plot.title = element_markdown(),
    plot.caption = element_markdown()
  )

hist_2020

# ggsave("hist_2020.png",
#        plot = hist_2020,
#        device = "png",
#        width = unit(16, "inch"),
#        height = unit(10, "inch"))
```

```{r}
hist_2021 <- ggplot(data = data_stunting_2021,
       aes(Prevalensi))+
  geom_density(
    aes(y = ..count..),
    size = 2,
    color = "slateblue")+
  labs(
    title = "Provinsi dengan Prevalensi Stunting Tinggi Cukup Dapat Diatasi",
    subtitle = "Tahun 2021",
    x = "Prevalensi (%)",
    caption = "**Sumber Data : Aksi Bangda Kemendagri**")+
  scale_y_continuous(limits =  c(0, 3),
                     breaks = seq(0, 3, 1))+
  scale_x_continuous(limits = c(0, 30),
                     breaks = seq(0, 30, 5))+
  theme(
    plot.title = element_markdown(),
    plot.caption =element_markdown()
  )

hist_2021

# ggsave("hist_2021.png",
#        plot = hist_2021,
#        device = "png",
#        width = unit(16, "inch"),
#        height = unit(10, "inch"))
```



# Visualisasi Peta

```{r}
ggthemr::ggthemr("fresh")

plot_2020 <- ggplot(data = peta_2020,
       aes(geometry = geometry,
           fill = Prevalensi))+
  geom_sf(alpha = 0.8)+
  geom_sf_label(
    data = peta_2020 %>%
      filter(
        Prevalensi > quantile(Prevalensi, 0.9)) %>%
      mutate(
        PROVINSI = str_to_title(PROVINSI)),
    aes(label = str_glue("{PROVINSI}\n{Prevalensi}%")),
    alpha = 0.35,
    nudge_y = 0.8)+
  labs(
    title = "Provinsi yang Mengalami Stunting Tinggi Relatif Mengumpul di Suatu Wilayah",
    subtitle = "Tahun 2020",
    fill = "Prevalensi Stunting (%)",
    x = "Longitude",
    y = "Latitude",
    caption = "**Sumber Data : Aksi Bangda Kemendagri**")+
  coord_sf()+
  ggsci::scale_fill_gsea(limits = c(0, 30))+
  theme(
    plot.title = element_markdown(size = 16),
    plot.subtitle = element_markdown(),
    legend.title = element_markdown(),
    legend.position = "top",
    plot.caption = element_markdown())
plot_2020

# ggsave("plot_2020.png",
#        plot = plot_2020,
#        device = "png",
#        width = unit(16, "inch"),
#        height = unit(10, "inch"))
```

```{r}
plot_2021 <- ggplot(data = peta_2021,
       aes(geometry = geometry,
           fill = Prevalensi))+
  geom_sf(alpha = 0.8)+
  geom_sf_label(
    data = peta_2021 %>%
      filter(
        Prevalensi > quantile(Prevalensi, 0.85),
        !(PROVINSI %in% c("NUSA TENGGARA TIMUR",
                          "NUSA TENGGARA BARAT"))) %>%
      mutate(
        PROVINSI = str_to_title(PROVINSI)),
    aes(label = str_glue("{PROVINSI}\n{Prevalensi}%")),
    alpha = 0.35,
    nudge_y = 0.8)+
  geom_sf_label(
    data = peta_2021 %>%
      filter(
        PROVINSI == "NUSA TENGGARA TIMUR") %>%
      mutate(
        PROVINSI = str_to_title(PROVINSI)),
    aes(label = str_glue("{PROVINSI}\n{Prevalensi}%")),
    alpha = 0.35,
    nudge_y = 0.8)+
  geom_sf_label(
    data = peta_2021 %>%
      filter(
        PROVINSI == "NUSA TENGGARA BARAT") %>%
      mutate(
        PROVINSI = str_to_title(PROVINSI)),
    aes(label = str_glue("{PROVINSI}\n{Prevalensi}%")),
    alpha = 0.35,
    nudge_y = -0.8)+
  labs(
    title = "Beberapa Provinsi Sudah Menangani Masalah Stunting dengan Cukup Baik",
    subtitle = "Tahun 2021",
    fill = "Prevalensi Stunting (%)",
    x = "Longitude",
    y = "Latitude",
    caption = "**Sumber Data : Aksi Bangda Kemendagri**")+
  coord_sf()+
  ggsci::scale_fill_gsea(limits = c(0, 30))+
  theme(
    plot.title = element_markdown(size = 16),
    plot.subtitle = element_markdown(),
    legend.title = element_markdown(),
    legend.position = "top",
    plot.caption = element_markdown())

plot_2021

# ggsave("plot_2021.png",
#        plot = plot_2021,
#        device = "png",
#        width = unit(16, "inch"),
#        height = unit(10, "inch"))
```

# Waterfall Chart

```{r}
diff_prevalensi <- data_stunting_2021$Prevalensi-data_stunting_2020$Prevalensi
diff_prevalensi

diff_stunting <- data.frame(
  Provinsi = data_stunting_2020$Provinsi,
  Prevalensi_diff = diff_prevalensi,
  Prevalensi2020 = data_stunting_2020$Prevalensi,
  Prevalensi2021 = data_stunting_2021$Prevalensi) %>%
  as_tibble() %>%
  mutate(
    Better = case_when(
      Prevalensi_diff <= 0 ~ "Better",
      Prevalensi_diff > 0 ~ "Worse")) %>%
  arrange(
    diff_prevalensi)
diff_stunting$id <- 34:1
diff_stunting

plot_diff <- diff_stunting %>%
  mutate(
    Provinsi = case_when(
      Provinsi == "DKI JAKARTA" ~ "DKI Jakarta",
      TRUE ~ str_to_title(Provinsi)),
    Provinsi = fct_reorder(Provinsi, id)) %>%
  ggplot()+
    geom_rect(
      aes(
        y = Provinsi,
        ymin = id-0.5,
        ymax = id+0.5,
        xmin = Prevalensi2020,
        xmax = Prevalensi2021,
        fill =  Better),
      color = "black") +
    labs(
      title = "Beberapa Provinsi Menunjukkan Perkembangan yang Baik dalam Menangani Masalah Stunting",
      subtitle = "Data Tahun 2020-2021",
      fill = "Progress",
      x = "Prevalensi Stunting",
      caption = "**Sumber Data : Aksi Bangda Kemendagri**")+
    scale_fill_manual(values = c("green", "red"))+
    scale_x_continuous(breaks = seq(0, 35, 5),
                       limits = c(0, 30))+
    theme(
      axis.title.y = element_blank(),
      plot.caption = element_markdown(),
      legend.position = "top")
plot_diff


# ggsave("plot_diff.png",
#        plot = plot_diff,
#        device = "png",
#        width = unit(16, "inch"),
#        height = unit(10, "inch"))
```

# Pie Chart

```{r}
data_balita <- read_excel("BBLR_Gizi.xlsx",
                          sheet = "BayiLahir") %>%
  pivot_longer(
    cols = `2018`:`2021`,
    names_to = "Tahun",
    values_to = "BayiLahir"
  )

data_balita

data_bblr <- read_excel("BBLR_Gizi.xlsx",
                        sheet = "BBLR")%>%
  pivot_longer(
    cols = `2018`:`2021`,
    names_to = "Tahun",
    values_to = "BBLR"
  )

data_bblr

data_bblr <- data_balita %>%
  left_join(data_bblr)

bblr_2021 <- data_bblr %>%
  filter(
    Tahun == 2021
  )
```

```{r}
bblr_2021 <- bblr_2021 %>%
  filter(
    `Kabupaten/Kota` != "DKI Jakarta") %>%
  mutate(
    CumuBayiLahir = cumsum(BayiLahir),
    noBBLR = BayiLahir - BBLR,
    lagCumuBayiLahir = lag(CumuBayiLahir)) %>%
  replace_na(replace = list(lagCumuBayiLahir = 0)) %>%
  rename(
    KabKot=`Kabupaten/Kota`
  )

bblr_2021
```

```{r}
# bblr_2021 %>%
#   select(KabKot, noBBLR, BBLR) %>%
#   pivot_longer(
#     cols = noBBLR:BBLR,
#     names_to = "Kondisi",
#     values_to = "n") %>%
#   ggplot() +
#     geom_bar(
#       aes(x = KabKot,
#           y = n,
#           fill = Kondisi),
#       stat = "identity"
#     )

plot_bblr <- bblr_2021 %>%
  mutate(
    per_bblr = BBLR/BayiLahir*100,
    KabKot = factor(KabKot),
    KabKot = fct_reorder(KabKot, per_bblr) %>%
      fct_rev()) %>%
  ggplot(aes(
        x = KabKot,
        y = per_bblr))+
    geom_bar(
      aes(fill = KabKot),
      stat = "identity",
      color = "black",
      alpha = 0.8)+
    geom_label(
      aes(label = str_glue("{round(per_bblr, 2)}%")),
      size = 5,
      fill = "lavender")+
    labs(
      title = "Kabupaten/Kota di Provinsi DKI seluruhnya memiliki persentase BBLR kurang dari 10%",
      subtitle = "Kabupaten Kepulauan Seribu memiliki persentase BBLR tertinggi",
      fill = "Kabupaten/Kota")+
    ggsci::scale_fill_startrek()+
    theme(
      legend.position = "top",
      axis.line = element_blank(),
      axis.title = element_blank(),
      axis.ticks = element_blank(),
      axis.text.y = element_blank(),
      axis.text.x = element_markdown(size = 14),
      legend.margin = margin(t = 10),
      panel.grid = element_blank())

# ggsave("plot_bblr.png",
#        plot_bblr,
#        device = "png",
#        width = unit(16, "inch"),
#        height = unit(10, "inch"))
```



